spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: read
          uri: http://localhost:8089
          predicates:
            - Path=/to-read
#            - Method=GET
        - id: test
          uri: http://localhost:8089
          predicates:
            - Path=/test
#            - Method=GET
        - id: testFeignCalling
          uri: http://localhost:8089
          predicates:
            - Path=/testFeignCalling
#            - Method=GET
        - id: testFeignCallingWithTimeOut
          uri: http://localhost:8089
          predicates:
            - Path=/testFeignCallingWithTimeOut
#            - Method=GET
